export {
  ENROLLMENT_QUOTA_ICONS,
  INFO_TABS_ICONS,
  LANDING_SECTION_TYPES,
  aboutSectionSchema,
  enrollmentQuotaSectionSchema,
  faqSectionSchema,
  footerSectionSchema,
  heroSectionSchema,
  infoTabsSectionSchema,
  landingConfigSchema,
  landingSectionSchema,
  pledgeSectionSchema,
  processSectionSchema,
  statsSectionSchema,
  testimonialsSectionSchema,
  type AboutSection,
  type EnrollmentQuotaIcon,
  type EnrollmentQuotaSection,
  type FaqSection,
  type FooterSection,
  type HeroSection,
  type InfoTabIcon,
  type InfoTabsSection,
  type LandingConfig,
  type LandingLink,
  type LandingSection,
  type LandingSectionType,
  type PledgeSection,
  type ProcessSection,
  type StatsSection,
  type TestimonialsSection,
} from "./sections";
